### ISSUE TITLE
Update default transforms to strictly follow oddworks resource specs

### ISSUE THREAD

**Issue by brkattk** [oddnetworks/oddworks-ooyala-provider#7]
The default transforms should strictly follow [oddworks resource specs](https://github.com/oddnetworks/oddworks/tree/master/docs/resources)

We should avoid polluting with all the external properties that don't map to oddworks resources.

**Comment by kixxauth** [comment]
The default transforms are used now more as suggestions or examples. Most users write their own transform implementations.
